workflows:
  react-native-ios-simulator:
    name: React Native iOS Debug (Simulador)
    environment:
      xcode: latest
      node: 20
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - node_modules
    scripts:
      - name: Instalar dependências JS
        script: |
          npm install
      - name: Instalar dependências iOS
        script: |
          cd ios
          pod install
      - name: Build para simulador (Debug)
        script: |
          xcodebuild \
            -workspace ios/SeuProjeto.xcworkspace \
            -scheme SeuProjeto \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath $CM_BUILD_DIR/build
    artifacts:
      - $CM_BUILD_DIR/build/Build/Products/Debug-iphonesimulator/**/*.app
